"""add leaked_codes table and affiliate active_promo_code

Revision ID: 9d115196b272
Revises: ccc1c19d5237
Create Date: 2026-07-02 17:19:19.959913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d115196b272'
down_revision: Union[str, Sequence[str], None] = 'ccc1c19d5237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaked_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('scan_type', sa.String(length=16), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leaked_codes_affiliate_id', 'leaked_codes', ['affiliate_id'], unique=False)
    op.create_index('ix_leaked_codes_code', 'leaked_codes', ['code'], unique=False)
    op.add_column('affiliates', sa.Column('active_promo_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliates', 'active_promo_code')
    op.drop_index('ix_leaked_codes_code', table_name='leaked_codes')
    op.drop_index('ix_leaked_codes_affiliate_id', table_name='leaked_codes')
    op.drop_table('leaked_codes')
    # ### end Alembic commands ###
